plugins {
    alias(libs.plugins.vinkit.jvm.library)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.pitest)
    `java-test-fixtures`
}

dependencies {
    api("com.github.vinaooo.vinkit:core:${providers.gradleProperty("vinkit.tag").get()}")
    implementation(libs.kotlinx.serialization.json)

    testFixturesImplementation(libs.kotlinx.coroutines.core)
}

kover {
    reports {
        verify {
            rule("Domain line coverage") {
                minBound(90)
            }
        }
    }
}

pitest {
    junit5PluginVersion.set(libs.versions.pitestJunit5)
    targetClasses.set(listOf("io.github.vinaooo.xo.domain.*"))
    // Generated by kotlinx.serialization; covered by round-trip tests instead.
    excludedClasses.set(listOf("*\$\$serializer"))
    // Whole games, slow under every mutant; AiTest covers the same code with exact checks.
    excludedTestClasses.set(listOf("io.github.vinaooo.xo.domain.AiStrengthTest"))
    timeoutConstInMillis.set(10_000)
    threads.set(2)
    jvmArgs.set(listOf("-Xmx512m"))
    outputFormats.set(listOf("HTML", "XML"))
    timestampedReports.set(false)
    mutationThreshold.set(80)
    coverageThreshold.set(90)
}
